spring.application.name=student-management-system

# DB Config
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=${LOGIN_USERNAME}
spring.security.user.password=${LOGIN_PASSWORD}